# Generated by Django 5.2.5 on 2025-09-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='limit',
            new_name='user_count',
        ),
    ]
