FROM python:3.11-slim

# --------------------
# Environment settings
# --------------------
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Fix locale (REQUIRED by Chrome)
RUN apt-get update && apt-get install -y locales && \
    locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

WORKDIR /app

# --------------------
# Install Chrome dependencies
# --------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget curl gnupg2 ca-certificates \
    build-essential \
    libpq-dev \
    # Chrome runtime deps
    libglib2.0-0 libgobject-2.0-0 libnspr4 libnss3 libnss3-tools libdbus-1-3 \
    libatk1.0-0 libatk-bridge2.0-0 libexpat1 libatspi2.0-0 libx11-6 libxcomposite1 \
    libxdamage1 libxext6 libxfixes3 libxrandr2 libgbm1 libxcb1 libxkbcommon0 libasound2 \
    libcups2 libu2f-udev libdrm2 xdg-utils \
    # Fonts (required for headless rendering)
    fonts-liberation fonts-noto-core fonts-noto-color-emoji \
    && rm -rf /var/lib/apt/lists/*

# --------------------
# Install Chromium (LTS version compatible with UC)
# --------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
    chromium \
    chromium-driver \
    && rm -rf /var/lib/apt/lists/*



# --------------------
# Increase /dev/shm for Chromium
# (prevents "cannot connect to chrome" crashes)
# --------------------
RUN mkdir -p /dev/shm && chmod 1777 /dev/shm

# --------------------
# Python requirements
# --------------------
COPY ../crm_core/dev_requirements.txt /app/requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt

# --------------------
# Copy project code
# --------------------
COPY ../crm_core /app

# Django settings
ENV DJANGO_SETTINGS_MODULE=crm_core.settings.development

# Celery worker startup
CMD ["celery", "-A", "crm_core", "worker", "-n", "marriott_worker", "-Q", "Marriott", "--loglevel=INFO"]
