# Generated by Django 5.2.5 on 2025-09-05 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawler', '0001_initial'),
        ('domain', '0001_initial'),
        ('gatekeeper', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization', models.BooleanField(default=True)),
                ('description', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_crawlers', models.ManyToManyField(related_name='allowed_crawler', to='crawler.crawler')),
                ('allowed_domains', models.ManyToManyField(related_name='allowed_domain', to='domain.domain')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='gatekeeper.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
