# Generated by Django 5.2.5 on 2025-09-05 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gatekeeper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(unique=True)),
                ('report_id', models.UUIDField(default=0, unique=True)),
                ('domain_name', models.CharField(max_length=255)),
                ('site_id', models.IntegerField(blank=True, null=True)),
                ('site_name', models.CharField(max_length=255)),
                ('retry_count', models.IntegerField(default=2)),
                ('parameter', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='gatekeeper.company')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawler_name', models.CharField(blank=True, max_length=200, null=True)),
                ('ins_ts', models.DateTimeField(blank=True, null=True)),
                ('requested_currency', models.CharField(default='US', max_length=100)),
                ('raw_response', models.JSONField(default=dict)),
                ('json_response', models.JSONField(default=dict)),
                ('hit_count', models.IntegerField(blank=True, null=True)),
                ('crawlStartTime', models.CharField(blank=True, max_length=100, null=True)),
                ('crawlEndTime', models.CharField(blank=True, max_length=100, null=True)),
                ('availability', models.BooleanField(default=False)),
                ('retry_count', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('errorDesc', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='apiservice.request')),
            ],
        ),
    ]
