# Networking
tcp-keepalive 300
timeout 0

# Clients
maxclients 2000

# Memory
maxmemory 1gb
maxmemory-policy allkeys-lru

# Persistence (cache use-case)
save ""
appendonly no

# Logging
loglevel notice
